"""Pack the approved Glass artwork into fixed-cell RGB565 firmware sprites.

This only extracts and downsamples the approved artwork; it does not redraw it.
Requires Pillow and NumPy. Run from any directory with Python 3.
"""
from pathlib import Path
import hashlib
import json

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets" / "flip_glass"
WIDTH, HEIGHT = 100, 128
# Exclude the specimen's labels and floor reflections. Reflections are rendered
# from the animated framebuffer on the device, so they follow the moving flaps.
BOXES = [
    (177, 54, 385, 285), (432, 54, 578, 285), (608, 54, 802, 285),
    (832, 54, 1030, 285), (1057, 54, 1263, 287),
    (167, 335, 385, 577), (391, 335, 588, 577), (616, 335, 810, 577),
    (831, 335, 1028, 578), (1053, 335, 1270, 578),
]


def main():
    source = ASSETS / "approved-design.png"
    board = Image.open(source).convert("RGB")
    assert board.size == (1536, 1024), "Crop coordinates belong to the approved board"
    cells = []
    for box in BOXES:
        glyph = board.crop(box)
        bounds = Image.fromarray((np.asarray(glyph).max(axis=2) > 24).astype("uint8") * 255).getbbox()
        assert bounds is not None
        glyph = glyph.crop(bounds)
        width = min(WIDTH - 2, round(glyph.width * (HEIGHT - 2) / glyph.height))
        glyph = glyph.resize((width, HEIGHT - 2), Image.Resampling.LANCZOS)
        cell = Image.new("RGB", (WIDTH, HEIGHT))
        cell.paste(glyph, ((WIDTH - width) // 2, 1))
        cells.append(cell)
    # Reuse the approved round glass colon, with a stable position and no blink.
    dot = board.crop((1336, 377, 1422, 464))
    bounds = Image.fromarray((np.asarray(dot).max(axis=2) > 24).astype("uint8") * 255).getbbox()
    dot = dot.crop(bounds).resize((24, 24), Image.Resampling.LANCZOS)
    colon = Image.new("RGB", (WIDTH, HEIGHT))
    colon.paste(dot, (38, 28))
    colon.paste(dot, (38, 78))
    cells.append(colon)
    atlas = Image.new("RGB", (WIDTH * 11, HEIGHT))
    values = []
    for index, cell in enumerate(cells):
        rgb = np.asarray(cell).copy()
        rgb[rgb.max(axis=2) <= 4] = 0
        cell = Image.fromarray(rgb)
        cell.save(ASSETS / f"{'colon' if index == 10 else index}.png")
        atlas.paste(cell, (index * WIDTH, 0))
        rgb = rgb.astype(np.uint16)
        values.extend((((rgb[:, :, 0] >> 3) << 11) | ((rgb[:, :, 1] >> 2) << 5) | (rgb[:, :, 2] >> 3)).ravel().tolist())
    atlas.save(ASSETS / "digits.png")
    rows = [", ".join(f"0x{value:04x}" for value in values[i:i+16]) + "," for i in range(0, len(values), 16)]
    (ROOT / "flip_glass_assets.h").write_text(
        "// Generated by tools/build_flip_glass_assets.py. Do not edit.\n#pragma once\n#include <cstdint>\n"
        "namespace flip_glass_assets {\n"
        f"constexpr int kWidth = {WIDTH}, kHeight = {HEIGHT}, kGlyphs = 11;\n"
        "// Opaque RGB565 on black; glass translucency is baked into the artwork.\n"
        "alignas(4) inline constexpr uint16_t kPixels[] = {\n" + "\n".join(rows) +
        "\n};\n}  // namespace flip_glass_assets\n", encoding="utf-8")
    (ASSETS / "manifest.json").write_text(json.dumps({
        "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "atlas_sha256": hashlib.sha256((ASSETS / "digits.png").read_bytes()).hexdigest(),
        "cell_width": WIDTH, "cell_height": HEIGHT, "glyphs": "0123456789:",
        "compiled_bytes": len(values) * 2, "source_boxes": BOXES,
    }, indent=2) + "\n", encoding="utf-8")
    print(f"Packed 10 approved digits and colon: {len(values) * 2:,} bytes in flash.")


if __name__ == "__main__":
    main()
