// Pack the approved canvas sprite masks and digit paths into firmware assets.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const {createCanvas,loadImage}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'..'),assets=path.join(root,'assets/pizza'),source=path.join(assets,'proposal');
const Pizza=require(path.join(source,'render.js'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function array(name,values,type,digits){
 let s=`alignas(4) inline constexpr ${type} ${name}[] = {\n`;
 for(let i=0;i<values.length;i+=16)s+=values.slice(i,i+16).map(v=>'0x'+v.toString(16).padStart(digits,'0')).join(',')+',\n';
 return s+'};\n';
}
(async()=>{
 const art=Pizza.prepare(createCanvas,await loadImage(path.join(source,'pepperoni-source.png')),await loadImage(path.join(source,'background-source.png')));
 const pixels=[];
 // Include a small baked shadow. The transparent border keeps rotated edges intact.
 for(let variant=0;variant<6;variant++){
  const tile=createCanvas(72,72),ctx=tile.getContext('2d');
  ctx.shadowColor='rgba(70,20,0,.4)';ctx.shadowBlur=64/31;ctx.shadowOffsetY=64/31;
  ctx.drawImage(art.sprites[variant][0],4,4);
  const data=ctx.getImageData(0,0,72,72).data;
  for(let x=0;x<72;x++)for(let y=0;y<72;y++){
   const i=(y*72+x)*4,a=data[i+3],r=Math.floor((data[i]*a+127)/255),g=Math.floor((data[i+1]*a+127)/255),b=Math.floor((data[i+2]*a+127)/255);
   pixels.push(((a<<24)|(r<<16)|(g<<8)|b)>>>0);
  }
 }
 // Rasterize settled/bite slices once, including their approved fractional
 // position and rotation. Store only nonempty column spans to save flash.
 const cached=[],spans=[],sprites=[],offsets=[];
 function cacheSlice(px,py,variant,phase,angle){
  const tile=createCanvas(40,40),ctx=tile.getContext('2d');
  Pizza.piece(ctx,art,20+px-Math.floor(px),20+py-Math.floor(py),variant,phase,1,angle);
  const rgba=ctx.getImageData(0,0,40,40).data,first=spans.length;
  for(let x=0;x<40;x++){
   let top=40,bottom=-1;
   for(let y=0;y<40;y++)if(rgba[(y*40+x)*4+3]){top=Math.min(top,y);bottom=y}
   if(bottom<top)continue;
   spans.push([x,top,bottom-top+1,cached.length]);
   for(let y=top;y<=bottom;y++){
    const i=(y*40+x)*4,a=rgba[i+3],rgb=[0,1,2].map(c=>Math.floor((rgba[i+c]*a+127)/255));
    cached.push(((a<<24)|(rgb[0]<<16)|(rgb[1]<<8)|rgb[2])>>>0);
   }
  }
  sprites.push([first,spans.length-first,Math.floor(px)-20,Math.floor(py)-20]);
 }
 for(let value=0;value<10;value++){
  offsets.push(sprites.length);
  Pizza.layouts[value].forEach((p,i)=>{
   for(let phase=0;phase<4;phase++)cacheSlice(p[0],p[1],(value*7+i*5)%6,phase,((i*17+value*7)%29-14)*Math.PI/180);
  });
 }
 const colon=sprites.length;cacheSlice(0,0,1,0,0);cacheSlice(0,0,4,0,0);
 const bg=[],rgba=art.bg.getContext('2d').getImageData(0,0,480,320).data;
 for(let x=0;x<480;x++)for(let y=319;y>=0;y--){const i=(y*480+x)*4,c=((rgba[i]>>3)<<11)|((rgba[i+1]>>2)<<5)|(rgba[i+2]>>3);bg.push(((c<<8)|(c>>8))&65535)}
 let h='// Generated by tools/build_pizza_assets.cjs. Do not edit.\n#pragma once\n#include <cstdint>\nnamespace pizza_assets {\n';
 h+='struct Point { float x, y; };\n';
 h+='inline constexpr uint8_t kCounts[] = {'+Pizza.layouts.map(p=>p.length).join(',')+'};\n';
 h+='inline constexpr Point kPoints[10][14] = {\n'+Pizza.layouts.map(points=>'{'+points.map(p=>'{'+p.map(v=>v.toFixed(5)+'f').join(',')+'}').join(',')+'}').join(',\n')+'\n};\n';
 h+='struct Span { uint8_t x,y,length; uint32_t offset; };\nstruct Sprite { uint32_t first; uint8_t count; int8_t x,y; };\n';
 h+='inline constexpr Span kSpans[] = {\n'+spans.map(s=>'{'+s.join(',')+'}').join(',\n')+'\n};\n';
 h+='inline constexpr Sprite kCached[] = {\n'+sprites.map(s=>'{'+s.join(',')+'}').join(',\n')+'\n};\n';
 h+='inline constexpr uint16_t kDigitOffsets[] = {'+offsets.join(',')+'};\ninline constexpr int kColon='+colon+';\n';
 h+=array('kSprites',pixels,'uint32_t',8)+array('kCachedPixels',cached,'uint32_t',8)+array('kBackground',bg,'uint16_t',4)+'}\n';
 const header=path.join(root,'pizza_assets.h');fs.writeFileSync(header,h);
 const manifest={status:'approved',size:[480,320],duration_ms:3600,sprite_size:72,compiled_bytes:pixels.length*4+cached.length*4+spans.length*8+sprites.length*8+bg.length*2+10*14*8+10+20,source_sha256:Object.fromEntries(['pepperoni-source.png','background-source.png','render.js'].map(n=>[n,sha(path.join(source,n))])),header_sha256:sha(header)};
 fs.writeFileSync(path.join(assets,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(manifest.compiled_bytes+' bytes of Pizza artwork');
})().catch(e=>{console.error(e);process.exit(1)});
