// Rebuild with Node.js and @napi-rs/canvas 0.1.100 (NODE_PATH may locate it).
// The exported PNG atlas is shared by the PC preview. Firmware uses trimmed
// columns in physical framebuffer order, avoiding runtime rotation or scaling.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { createCanvas } = require('@napi-rs/canvas');
const { explosionFrame } = require('./car_explosion_art.cjs');
const root = path.resolve(__dirname, '..');
const output = path.join(root, 'assets/cars/explosion');
fs.mkdirSync(output, { recursive: true });
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const columns = [], frames = [], pixels = [], images = [];
const atlas = createCanvas(6 * 128, 128 + 72);
const atlasContext = atlas.getContext('2d');
const large = Array.from({ length: 6 }, (_, frame) => explosionFrame(createCanvas, frame));
for (const size of [128, 72]) {
  for (let frame = 0; frame < 6; ++frame) {
    const tile = createCanvas(size, size), ctx = tile.getContext('2d');
    ctx.drawImage(large[frame], 0, 0, size, size);
    atlasContext.drawImage(tile, frame * 128, size === 128 ? 0 : 128);
    const png = tile.toBuffer('image/png');
    const file = `${size === 128 ? 'digit' : 'colon'}-${frame}.png`;
    fs.writeFileSync(path.join(output, file), png);
    images.push({ file, sha256: hash(png), size, frame });
    const rgba = ctx.getImageData(0, 0, size, size).data;
    frames.push({ columnOffset: columns.length, size });
    for (let x = 0; x < size; ++x) {
      let begin = size, end = 0;
      for (let nativeX = 0; nativeX < size; ++nativeX) {
        const y = size - 1 - nativeX;
        if (rgba[(y * size + x) * 4 + 3] >= 3) {
          begin = Math.min(begin, nativeX); end = nativeX + 1;
        }
      }
      const offset = pixels.length;
      if (begin < end) {
        for (let nativeX = begin; nativeX < end; ++nativeX) {
          const index = ((size - 1 - nativeX) * size + x) * 4;
          pixels.push(((rgba[index + 3] << 24) | (rgba[index] << 16) |
                       (rgba[index + 1] << 8) | rgba[index + 2]) >>> 0);
        }
      }
      columns.push({ offset, begin: begin < end ? begin : 0, count: Math.max(0, end - begin) });
    }
  }
}
const atlasPng = atlas.toBuffer('image/png');
fs.writeFileSync(path.join(output, 'atlas.png'), atlasPng);
fs.writeFileSync(path.join(root, '../pc/assets/car_explosion.png'), atlasPng);
let header = `// Generated by tools/build_car_explosion.cjs. Do not edit by hand.
#pragma once
#include <cstdint>
namespace car_explosion_assets {
constexpr uint16_t kImpactDelayMs = 90, kDurationMs = 350;
constexpr uint8_t kFrameCount = 6;
struct Column { uint32_t offset; uint8_t begin, count; };
struct Frame { uint16_t columnOffset; uint8_t size; };
inline constexpr Frame kFrames[] = {
${frames.map(f => `  {${f.columnOffset}, ${f.size}},`).join('\n')}
};
inline constexpr Column kColumns[] = {
${columns.map(c => `  {${c.offset}, ${c.begin}, ${c.count}},`).join('\n')}
};
// ARGB8888, read once per pixel; columns follow increasing native display X.
inline constexpr uint32_t kPixels[] = {
`;
for (let i = 0; i < pixels.length; i += 10)
  header += '  ' + pixels.slice(i, i + 10).map(p => `0x${p.toString(16).padStart(8, '0')}u`).join(', ') + ',\n';
header += '};\n}  // namespace car_explosion_assets\n';
fs.writeFileSync(path.join(root, 'car_explosion_assets.h'), header);
const manifest = {
  approved: '2026-09-13 larger explosion preview',
  approved_preview_sha256: hash(fs.readFileSync(path.join(output, 'approved-preview.html'))),
  source_sha256: hash(fs.readFileSync(path.join(__dirname, 'car_explosion_art.cjs'))),
  generator: '@napi-rs/canvas 0.1.100', frames: 6, impact_delay_ms: 90, duration_ms: 350,
  digit_size: 128, colon_size: 72, atlas_sha256: hash(atlasPng),
  header_sha256: hash(Buffer.from(header)), images,
  pixel_count: pixels.length, compiled_bytes: pixels.length * 4 + columns.length * 8 + frames.length * 4
};
fs.writeFileSync(path.join(output, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
process.stdout.write(`Built six explosion frames at 128px and 72px; ${manifest.compiled_bytes} compiled bytes.\n`);
