"""Pack approved light-glass PNGs into native-order firmware artwork.

This converts the approved sprite pixels without redrawing the artwork.
Requires Pillow and NumPy. Output is deterministic; no network access is used.
"""
from pathlib import Path
import hashlib
import json
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets" / "flip_glass_light"
SOURCE = ASSETS / "proposal"


def array(name, values, kind, digits):
    values = values.ravel().tolist()
    rows = [", ".join(f"0x{v:0{digits}x}" for v in values[i:i+16]) + "," for i in range(0, len(values), 16)]
    return f"alignas(4) inline constexpr {kind} {name}[] = {{\n" + "\n".join(rows) + "\n};\n"


def main():
    source_names = [f"{n}.png" for n in range(10)] + ["colon.png", "background.png"]
    sprites = []
    for name in source_names[:11]:
        rgba = np.asarray(Image.open(SOURCE / name).convert("RGBA")).astype(np.uint32)
        assert rgba.shape == (128, 100, 4)
        alpha = rgba[:, :, 3]
        # Premultiplied ARGB, column-major for the panel/PSRAM traversal.
        rgb = (rgba[:, :, :3] * alpha[:, :, None] + 127) // 255
        packed = (alpha << 24) | (rgb[:, :, 0] << 16) | (rgb[:, :, 1] << 8) | rgb[:, :, 2]
        sprites.append(packed.T.ravel())
    bg = np.asarray(Image.open(SOURCE / "background.png").convert("RGB")).astype(np.uint16)
    assert bg.shape == (320, 480, 3)
    bg565 = ((bg[:, :, 0] >> 3) << 11) | ((bg[:, :, 1] >> 2) << 5) | (bg[:, :, 2] >> 3)
    # Store already byte-swapped, rotated pixels for direct restoration/transfers.
    native = np.rot90(bg565, -1)
    native = ((native << 8) | (native >> 8)).astype(np.uint16)
    fade = np.array([round(255 * .44 * (1-y/100)**1.25) for y in range(100)], dtype=np.uint8)
    header = "// Generated by tools/build_flip_glass_light_assets.py. Do not edit.\n#pragma once\n#include <cstdint>\nnamespace flip_glass_light_assets {\n"
    header += "constexpr int kWidth = 100, kHeight = 128, kGlyphs = 11;\n"
    header += array("kGlyphsARGB", np.concatenate(sprites), "uint32_t", 8)
    header += array("kBackground", native, "uint16_t", 4)
    header += array("kReflectionFade", fade, "uint8_t", 2)
    header += "}  // namespace flip_glass_light_assets\n"
    (ROOT / "flip_glass_light_assets.h").write_text(header, encoding="utf-8", newline="\n")
    manifest = {
        "status": "approved", "cell_width": 100, "cell_height": 128,
        "glyphs": "0123456789:", "compiled_bytes": 11*100*128*4+480*320*2+100,
        "source_sha256": {name: hashlib.sha256((SOURCE / name).read_bytes()).hexdigest() for name in source_names},
        "header_sha256": hashlib.sha256((ROOT / "flip_glass_light_assets.h").read_bytes()).hexdigest(),
    }
    (ASSETS / "manifest.json").write_text(json.dumps(manifest, indent=2)+"\n", encoding="utf-8", newline="\n")
    print(f"Packed approved light-glass artwork: {manifest['compiled_bytes']:,} bytes in flash.")


if __name__ == "__main__":
    main()
